language: python
services: redis-server
python:
 - "2.7"
 - "3.3"
env:
 - FLASK_VERSION=0.9 REDIS_VERSION=2.6.2
 - FLASK_VERSION=0.9 REDIS_VERSION=2.7.4
 - FLASK_VERSION=0.9 REDIS_VERSION=2.10.3
 - FLASK_VERSION=0.10 REDIS_VERSION=2.6.2
 - FLASK_VERSION=0.10 REDIS_VERSION=2.7.4
 - FLASK_VERSION=0.10 REDIS_VERSION=2.10.3
install:
 - "pip install -r requirements.txt"
 - "pip install -I Flask==$FLASK_VERSION"
 - "pip install -I redis==$REDIS_VERSION"
script: "invoke travisci"
matrix:
  exclude:
    - python: "3.3"
      env: FLASK_VERSION=0.9 REDIS_VERSION=2.6.2
    - python: "3.3"
      env: FLASK_VERSION=0.9 REDIS_VERSION=2.7.4
    - python: "3.3"
      env: FLASK_VERSION=0.9 REDIS_VERSION=2.10.3
